name: UI-automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.job}} started on ${{matrix.env}}"
      - run: bash send_notification.sh “{{github.job}} {{matrix.env}}” 0 
    
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.job}} started on ${{matrix.env}}"
      - run: bash send_notification.sh “{{github.job}} {{matrix.env}}” 0 
      
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.job}} started on ${{matrix.env}}"
      - run: bash send_notification.sh “{{github.job}} {{matrix.env}}” 0 
