name: UI-automation CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.job}} started on ${{matrix.env}}"
      - run: bash send_notification.sh “{{github.job}} {{matrix.env}}” $? 
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.job}} started on ${{matrix.env}}"
      - run: bash send_notification.sh “{{github.job}} {{matrix.env}}” $? 
      
  test:
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.job}} started on ${{matrix.env}}"
      - run: |
          docker network create -d bridge test-automation-setup 
          docker build -t artursjlazdins/mvn_tests
          docker-compose up
          bash send_notification.sh “{{github.job}} {{matrix.env}}” $?


